from model.CNN_Key_Query_Categorisation import CNN_Key_Query_Categorisation
from model.CNN_Key_Query_Triplet import CNN_Key_Query_Triplet
from model.CNN_Siamise_Categorisation import CNN_Siamise_Categorisation
from model.CNN_Siamise_Triplet import CNN_Siamise_Triplet